version: '3.4'
services:
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD:admin

  todoapi:
    build: ./todoapi/
    restart: always
    ports:
      - '5000:80'
    depends_on:
      - mariadb

  todoapp:
    build: ./todoapp/
    ports:
      - '3000:80'
    depends_on:
      - todoapi

  keycloak:
    image: jboss/keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - DB_VENDOR=h2
    volumes:
      - ./infra/realm.json:/tmp/realm.json

